---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud-platform

resources:
  - resource-quotas.yaml
  - limit-ranges.yaml
  - priority-classes.yaml

commonLabels:
  app.kubernetes.io/name: policies
  app.kubernetes.io/component: governance
  app.kubernetes.io/part-of: nextcloud-platform
  app.kubernetes.io/managed-by: argocd

