---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud-platform

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - pdb.yaml
  - configmap.yaml
  - networkpolicy.yaml
  - externalsecret.yaml

commonLabels:
  app.kubernetes.io/name: pgbouncer
  app.kubernetes.io/component: database-proxy
  app.kubernetes.io/part-of: nextcloud-platform
  app.kubernetes.io/managed-by: argocd

