---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud-platform

resources:
  - clustersecretstore.yaml
  - rbac.yaml

commonLabels:
  app.kubernetes.io/name: external-secrets
  app.kubernetes.io/component: secrets-management
  app.kubernetes.io/part-of: nextcloud-platform
  app.kubernetes.io/managed-by: argocd

